GET https://crudcrud.com/api/962812dda5ca4589a0fcaa885bf98dbc/unicorn/670c28f8a0a8cd03e818a731
Accept: application/json

###
POST https://crudcrud.com/api/962812dda5ca4589a0fcaa885bf98dbc/unicorn
Content-Type: application/json

{
  "name": "2",
  "tail_colour": "mmm"
}

###

PUT https://crudcrud.com/api/962812dda5ca4589a0fcaa885bf98dbc/unicorn/670c28f8a0a8cd03e818a731
Content-Type: application/json

{
  "tail_colour": "ivory"
}

###

DELETE https://crudcrud.com/api/962812dda5ca4589a0fcaa885bf98dbc/unicorn/670b0d5ea0a8cd03e818a60a
Accept: application/json

###
GET https://crudcrud.com/api/962812dda5ca4589a0fcaa885bf98dbc/unicorn/
Accept: application/json

###